org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=worldlearns
mod_name=World Learns From You
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.ratinmv.worldlearns
mod_authors=Ratin
mod_description=The Minecraft world learns from your playstyle. Mobs adapt to repeated player behavior, including mobs added by other mods.
