modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="worldlearns"
version="${file.jarVersion}"
displayName="World Learns From You"
authors="Ratin"
description='''The Minecraft world learns from your playstyle. Mobs adapt to repeated player behavior, including mobs added by other mods.'''

[[dependencies.worldlearns]]
modId="forge"
mandatory=true
versionRange="[47.4.10,)"
ordering="NONE"
side="BOTH"

[[dependencies.worldlearns]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
